"""
Email delivery via Amazon SES.
"""
import logging
import boto3

logger = logging.getLogger()

ses = boto3.client("ses", region_name="us-east-1")


def send_email(to_address: str, from_address: str, subject: str, body: str) -> dict:
    """
    Send the morning brief via Amazon SES.
    """
    try:
        response = ses.send_email(
            Source=from_address,
            Destination={
                "ToAddresses": [to_address]
            },
            Message={
                "Subject": {
                    "Data": subject,
                    "Charset": "UTF-8"
                },
                "Body": {
                    "Text": {
                        "Data": body,
                        "Charset": "UTF-8"
                    },
                    "Html": {
                        "Data": _format_html(subject, body),
                        "Charset": "UTF-8"
                    }
                }
            }
        )
        
        logger.info("Email sent. MessageId: %s", response["MessageId"])
        return response
        
    except Exception as e:
        logger.error("SES send failed: %s", str(e))
        raise


def _format_html(subject: str, body: str) -> str:
    """Convert plain text brief to styled HTML email."""
    html_body = body.replace("\n", "<br>")
    
    return f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f7f7f7;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">🌅 DayForge</h1>
        <p style="color: rgba(255,255,255,0.8); margin: 4px 0 0; font-size: 14px;">
            Your AI Morning Brief
        </p>
    </div>
    <div style="background: white; padding: 24px; border-radius: 0 0 12px 12px; 
                box-shadow: 0 2px 8px rgba(0,0,0,0.1); line-height: 1.6; font-size: 15px; color: #333;">
        {html_body}
    </div>
    <p style="text-align: center; color: #999; font-size: 12px; margin-top: 16px;">
        Generated by DayForge Agent • Powered by Amazon Bedrock
    </p>
</body>
</html>
"""
